### ISSUE TITLE
Health Check Memory panel is wrong

### ISSUE THREAD

**Issue by xxPhuNguyenxx** [criblio/criblvision#25]
FYI, the query for the memory used is too low. This dataset is giving memory usage per worker process . When you run an average on each wp, its going to be extremely low

`set_cribl_internal_log_index` `set_cribl_log_sourcetype` $environment_filter$ $host_filter$ $worker_group_event_filter$ channel=server message="_raw stats" 
| stats avg(mem.rss) AS memRss

just a thought, do something like this but would need to make the bin _time maybe more dynamic in case user is querying by larger time span. 

`set_cribl_internal_log_index` `set_cribl_log_sourcetype` $environment_filter$ $host_filter$ $worker_group_event_filter$ channel=server message="_raw stats" 
      | bin _time span=1m 
      | stats sum(mem.rss) as "mem_rss" by _time host 
| timechart avg(mem_rss) as memRss useother=f by host

**Comment by DavidSheridan** [comment]
Good catch, thanks for raising this @xxPhuNguyenxx! Will implement a fix for this.

**Comment by DavidSheridan** [comment]
Fix was pushed as part of CriblVision version 3.2.1.
