### ISSUE TITLE
Spelling issue in filename 'environment_assets.csv'

### ISSUE THREAD

**Issue by smalluk** [criblio/criblvision#31]
Spelt envrionment instead of environment in Readme
https://github.com/criblio/criblvision/blob/main/criblvision-for-criblsearch/README.md#populate-environment-assets-lookup

**Comment by DavidSheridan** [comment]
Thanks! Fixed in https://github.com/criblio/criblvision/commit/50281bffd9803db4c2df93449a1cd965d7492408.
